# Generated by Django 6.1.1 on 2026-09-11 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(help_text='The source PDF uploaded by the user', upload_to='pdfs/original/%Y/%m/%d/')),
                ('translated_file', models.FileField(blank=True, help_text='The newly generated translated PDF', null=True, upload_to='pdfs/translated/%Y/%m/%d/')),
                ('source_language', models.CharField(default='en', max_length=10)),
                ('target_language', models.CharField(default='bn', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF translation',
                'verbose_name_plural': 'PDF Translations',
                'ordering': ['-created_at'],
            },
        ),
    ]
