# Generated by Django 6.1.1 on 2026-09-11 16:03

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFWatermark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(help_text='Source PDF uploaded by user', upload_to='pdfs/watermark/original/%Y/%m/%d/')),
                ('watermarked_file', models.FileField(blank=True, help_text='Newly generated watermarked PDF', null=True, upload_to='pdfs/watermark/output/%Y/%m/%d/')),
                ('text', models.CharField(help_text='Watermark text, e.g. "CONFIDENTIAL"', max_length=255)),
                ('position', models.CharField(choices=[('top-left', 'Top Left'), ('top-center', 'Top Center'), ('top-right', 'Top Right'), ('center', 'Center'), ('bottom-left', 'Bottom Left'), ('bottom-center', 'Bottom Center'), ('bottom-right', 'Bottom Right')], default='center', help_text='Position on page', max_length=20)),
                ('opacity', models.FloatField(default=0.25, help_text='Opacity between 0.0 and 1.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('color', models.CharField(default='#FF0000', help_text='Hex color, e.g. "#FF0000"', max_length=7)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF Watermark',
                'verbose_name_plural': 'PDF Watermarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
